export const titles = [
	"The Sealed Oath",
	"Wild and Wicked",
	"Legacy Retreating",
	"The Song of the Eight",
	"Death of the Winged Ferret",
	"Brazen and Buff",
	"Cross and the Serpent",
	"Dressed for Sorrow",
	"The Ghost in the West",
	"Crimson Instinct",
	"The Blade in the Gorge",
	"Crisis of Lust",
	"Electric Dust",
	"Present Of The Diamond Tales Of The South",
	"Crazy With The Professional Mouse Of The Land",
	"Enchanted By The Laughing Guardians",
	"Gift From The Cracked Cow",
	"Rough Stories",
	"Caring For The Silent Sparks Of Autumn",
	"Present Of The Which Voyages",
	"Elemental Officers Of Doom",
	"Fear Of The Dangerous Girls Of The North",
	"Burning Cup Of Spring",
	"Adventure Of The Missing Hunter Of Wind",
	"Crazy At The Dangerous Man Of Tomorrow",
	"Dangerous Door",
	"Puzzling With The Laughing Home Of My Mind",
	"Cute With The Missing Officer Of The Blues",
	"Helping The Captured Past With Horns",
	"Boring At The Diamond Founder Of The Future",
	"Giving With The Only Peasants Of The Ocean",
	"Cold Duck Of History",
	"Sacred Lord Of The Swamp",
	"Invisible Little Dragon Of The Swamp",
	"Lost Agents Dressed In Black",
	"Laughing Basement Of Time",
	"Cooking With The Dangerous Watch",
	"Back To The Hot Assassin Of The Past",
	"Broken Butterfly",
	"Sacred Heart",
	"Ragged Boyfriend",
	"Learning With The Stolen Kids Of The South",
	"Seventh Baker Of The North",
	"First Girl Of The Lost Ones",
	"Learning With The Every Memory Of The Undead",
	"Falling Sheep Of My Admiration",
	"Amazing Life Of The Dying Heirs Of Fire",
	"Chasing The Forgotten Window Of The Wind",
	"Playing With The Stripped Man",
	"Finding The Kissing Destiny Of The Caves",
	"Happy With The Devoted Girls With Curly Hair",
	"Loved By The Dwindling Prince With Money",
	"Giving With The Silver Child",
	"Amazing Life Of The Erect Pirates",
	"Colors Of The Sleeping Spark Of Hope",
	"A Day With The Purple Man Of Freedom",
	"Bewitched By The Wanton Someone",
	"Afraid Of The Hidden Girl",
	"Cleaning With The Stripped Guardians",
	"Cute With The Trembling Souls Without Desire",
	"Drawing With The Last Words Of The Void",
	"Cold Spies Of The Lost Ones",
	"Cute With The Dwindling Rat With Immortality",
	"Missing Heirs Of Lust",
	"Cleaning With The Hard Baker With Tradition",
	"Happy With The Luscious Sword Of Paradise",
	"White Flower Of Twilight",
	"Fear Of The Entwined Foreigners With Skills",
	"Back To The Missing Slaves Without Time",
	"Cracked Person Of Dusk",
	"Fear Of The Weeping Supporter Without Desire",
	"Burning Snowman",
	"Free With The First Princess Of Summer",
	"Drawing With The Dying Ice Of The Curse",
	"Back With The Invisible Slave Without Glory",
	"First Opponent Of Joy",
	"Last Pirates Of My Imagination",
	"Giving With The Dwindling Snowman Of The Frontline",
	"Crazy With The Green Dreamer",
	"Playing With The Dying Women Without Shame",
];

export const names = [
	"Luka Livesay",
	"Advait Cosme",
	"Amarianna Chon",
	"Tymber Stapp",
	"Jessi Durden",
	"Gaige Sisson",
	"Vivien Lunsford",
	"Connor Brooks",
	"Demi Quinones",
	"Yamilet Seibert",
	"Calissa Mounts",
	"Evan Henderson",
	"Aiyana Cornell",
	"Jan Chao",
	"Praise Hibbert",
	"Timmy Cozart",
	"Colten Noel",
	"Tyriq Richburg",
	"Kamber Almendarez",
	"Arial Mcsweeney",
	"Josias Archuleta",
	"Kobie Gallion",
	"Bibiana Klink",
	"Lux Caddell",
	"Kyngston Tingle",
	"Graison Hallam",
	"Delany Cory",
	"Florence Sepulveda",
	"Maliki Deweese",
	"Whitley Amador",
	"Charissa Dice",
	"Kasia Cloyd",
	"Carter Sanchez",
	"Eliezer Bartholomew",
	"Jozlyn Goodell",
	"Vann Diego",
	"Legend Mulkey",
	"Jaasiel Freeze",
	"Frederick Mackey",
	"Selene Joiner",
	"Marciano Rana",
	"Jacolby Brittingham",
	"Dexton Widner",
	"Snow Gault",
	"Kenzlee Custer",
	"Dulce Harden",
	"Ashlyn Clay",
	"Nawaf Ostrom",
	"Adya Romer",
	"Trapper Teller",
	"Reegan Boatman",
	"Italy Biddle",
	"Gwendolen Julius",
	"Sofiya Franzen",
	"Johndavid Zalewski",
	"Hollie Clem",
	"Annalyse Wojcik",
	"Kenzi Ragsdale",
	"Viraaj Sheriff",
	"Syncere Eliason",
	"Aedan Mcnulty",
];
